[[rule]]
toolName = "write_file"
decision = "allow"
priority = 100

[[rule]]
toolName = "replace"
decision = "allow"
priority = 100

[[rule]]
toolName = "web_fetch"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [
  "mkdir",
  "grep",
  "ls",
  "echo",
  "find",
  "cat",
  "cp",
  "df",
  "tree"
]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "coca", "ast-grep", "jq", "graphviz" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "go", "java", "mvn" ]

[[rule]]
toolName = "activate_skill"
decision = "allow"
priority = 100
